# -*- coding: utf-8 -*-
"""дз2 комп зрение.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153pMVgWkL0ouD093RsM9FiY5tZtCCmHr
"""

!pip install umap-learn

import numpy as np
import tensorflow as tf

from umap import UMAP
from matplotlib import pyplot as plt
from skimage import io

"""# 1. Вывод фильтров свертки

В этом разделе нужно:

1) создать модель VGG16 с весами 'imagenet'

2) загрузить свою зартинку в переменную при помощи skiamge.io.imread или plt.imread и тд

3) создать новую модель нейронной сети с выходами, которые соответствуют выходам сверточных слоев с названиями ['block1_pool', 'block2_pool', 'block3_pool', 'block4_pool', 'block5_pool']

4) отправить новой модели свою картинку и сохранить возвращенный результат

5) вывести по одному фильтру свертки для каждого сверточного слоя при помощи plt.imshow
"""

from skimage.io import imread

vgg = tf.keras.applications.VGG16(weights='imagenet', include_top=False)
img = imread('/content/capy.jpg')
layers_name = ['block1_pool', 'block2_pool', 'block3_pool', 'block4_pool', 'block5_pool']
outputs = [vgg.get_layer(i).output for i in layers_name]
model = tf.keras.models.Model(inputs=vgg.input, outputs=outputs)

img = np.expand_dims(img, axis=0)
result = model.predict(img)

for i, block in enumerate(['block1_pool', 'block2_pool', 'block3_pool',  'block4_pool', 'block5_pool']):
    plt.figure()
    plt.imshow(result[i][0, :, :, 0])
    plt.title(block)
    plt.axis('off')
    plt.show()

"""# 2. Выбор датасета

1) Переходим на [сайт](https://www.tensorflow.org/datasets/catalog/overview) датасетов tensorflow и выбираем датасет с изображениями для классификации

2) загружаем датасет в переменную
"""

import tensorflow_datasets as tfds
dataset, info = tfds.load('oxford_iiit_pet', split='train', as_supervised=True)

"""# 3. Получение признаков для всего датасета

1) создаем модель VGG16 без последнего классифицирубщего слоя (include_top=False)

2) В цикле загружаем картинки нашего датасета в модель и сохраняем вектор признаков (эмбеддинг)
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from tensorflow.keras.applications.vgg16 import preprocess_input

model = tf.keras.applications.VGG16( include_top=False)
features = []
dataset = dataset.take(5000)
for image, label in dataset:
    image = tf.cast(image, tf.float32)
    image = tf.image.resize(image, (224, 224))
    image = preprocess_input(image)
    feature_vector = model.predict(np.expand_dims(image, axis=0))
    features.append(feature_vector.flatten())

np.save('features.npy', features)

"""# 4. Вывод признаков датасета на двумерную плоскость

1) создаем модель для понижения размерности и загружаем в нее вектора признаков изображений. Размер входных данных для Umap - (N_images, N_features). Документация [Umap](https://umap-learn.readthedocs.io/en/latest/basic_usage.html)

2) при помощи plt.scatter выводим выводит признаки на двумерную плоскость так, чтобы у каждого класса был свой цвет

(!) обратите внимание, что признаки изображений хранятся в тензорах Tensorflow. Перед их обработкой нужно получить их версии в numpy
"""

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import umap

seed = 51
# создаем модель Umap
umap_2d = umap.UMAP()

# понижаем размерность
umaped_vct_2d = umap_2d.fit_transform(features)
x,y=umaped_vct_2d[:,0],umaped_vct_2d[:,1]

plt.figure(figsize=(5,5))
plt.scatter(x,y)


plt.show()

x1=np.random.uniform(0,10,10)
y1=np.random.normal(2,10,10)

x2=np.random.uniform(0,10,10)
y2=np.random.normal(1,8,10)

plt.figure(figsize=(5,5))

plt.scatter(x1,y1)
plt.scatter(x2,y2)

plt.legend(['first scatter class','second scatter class'])
plt.show()

"""Как понять, что все хорошо? Если все шаги были выполнены верно, то на двумерной плоскости у вас должны появиться K кластеров вашего датасета, где каждый кластер будет отвечать за свой класс в датасета. Т.е. собачки будут отдельно, котики отдельно и тд"""